// rumexstore-angular/src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { ICategory } from '../interfaces';
import { selectCategories, selectCategoriesError, selectCategoriesLoading, selectCategoriesTotal } from '../shop/state/shop.selectors';
import { Store, select } from '@ngrx/store';
import { Observable, Subscription } from 'rxjs';
import { AppState } from '../state/app.state';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent implements OnInit {
  categories: Array<ICategory> = [];
  public categoriesTotal!: number;
  private subscription: Subscription = new Subscription();
  public loading!: boolean;
  public error$!: Observable<any>;

  public rowHeight!: string;
  public breakpoint!: number;
  public isMobile!: boolean;
  public isTablet!: boolean;

  protected stackoverflowUrl: string =
    'https://stackoverflow.com/users/1791913/faisal?tab=profile';
  protected linkedinUrl: string = 'https://www.linkedin.com/in/mohammadfaysal/';
  protected fiverrUrl: string = 'https://www.fiverr.com/faisalmuhammad_';
  protected facebookUrl: string = 'https://www.facebook.com/phaysall';
  protected twitterUrl: string = 'https://twitter.com/faisssallll';
  protected githubUrl: string = 'https://github.com/faisalmuhammad';
  protected googleUrl: string = 'https://plus.google.com/+MuhammadFaisal04';
  constructor(private store: Store<AppState>) {}
  onResize(event: any) {
    if (event.target.innerWidth > 992) {
      this.breakpoint = 6;
      this.rowHeight = '55px';
      this.isMobile = false;
      this.isTablet = false;
    } else if (event.target.innerWidth > 576) {
      this.breakpoint = 3;
      this.rowHeight = '50px';
      this.isMobile = false;
      this.isTablet = true;
    } else {
      this.breakpoint = 1;
      this.rowHeight = '60px';
      this.isMobile = true;
      this.isTablet = false;
    }
  }
  ngOnInit() {
    if (window.innerWidth > 992) {
      this.breakpoint = 6;
      this.rowHeight = '55px';
      this.isMobile = false;
      this.isTablet = false;
    } else if (window.innerWidth > 576) {
      this.breakpoint = 3;
      this.rowHeight = '50px';
      this.isMobile = false;
      this.isTablet = true;
    } else {
      this.breakpoint = 1;
      this.rowHeight = '60px';
      this.isMobile = true;
      this.isTablet = false;
    }
    this.store
      .pipe(select(selectCategories))
      .subscribe((categories) => (this.categories = categories));
    this.store
      .pipe(select(selectCategoriesTotal))
      .subscribe((total) => (this.categoriesTotal = total));
    this.subscription.add(
      this.store.pipe(select(selectCategoriesLoading)).subscribe((loading) => {
        this.loading = loading;
      }),
    );
    this.error$ = this.store.pipe(select(selectCategoriesError));
  }
}

<footer class="main-footer" (window:resize)="onResize($event)">
  <mat-grid-list
    cols="6"
    [cols]="breakpoint"
    [rowHeight]="rowHeight"
    gutterSize="0"
  >
    <mat-grid-tile rowspan="4" colspan="1">
      <mat-card>
        <mat-card-header>
          <mat-card-title>
            <h3>CATEGORIES</h3>
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <mat-list role="list">
            <mat-list-item *ngFor="let item of categories" role="listitem"
              ><a [routerLink]="['products', item.id]">
                {{ item.categoryName }}
              </a>
            </mat-list-item>
          </mat-list>
        </mat-card-content>
      </mat-card>
    </mat-grid-tile>
    <mat-grid-tile rowspan="4" colspan="1">
      <mat-card>
        <mat-card-header>
          <mat-card-title>
            <h3>STYLES</h3>
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <mat-list role="list">
            <mat-list-item role="listitem">
              <a href="/">Athletic</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Casual</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Dress</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Everyday</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Other Days</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Alternative</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Otherwise</a>
            </mat-list-item>
          </mat-list>
        </mat-card-content>
      </mat-card>
    </mat-grid-tile>
    <mat-grid-tile rowspan="4" colspan="1">
      <mat-card>
        <mat-card-header>
          <mat-card-title>
            <h3>OTHER</h3>
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <mat-list role="list">
            <mat-list-item role="listitem">
              <a href="/">Link</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Another link</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Link again</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Try this</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Don't you dare</a>
            </mat-list-item>
            <mat-list-item role="listitem">
              <a href="/">Oh go ahead</a>
            </mat-list-item>
          </mat-list>
        </mat-card-content>
      </mat-card>
    </mat-grid-tile>
    <mat-grid-tile rowspan="4" [colspan]="isMobile ? '1' : '3'">
      <mat-card>
        <mat-card-header>
          <mat-card-title>
            <h3>ABOUT US</h3>
          </mat-card-title>
        </mat-card-header>
        <mat-card-content
          ><p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
            euismod congue bibendum. Aliquam erat volutpat. Phasellus eget justo
            lacus. Vivamus pharetra ullamcorper massa, nec ultricies metus
            gravida egestas. Duis congue viverra arcu, ac aliquet turpis rutrum
            a. Donec semper vestibulum dapibus. Integer et sollicitudin metus.
            Vivamus at nisi turpis. Phasellus vel tellus id felis cursus
            hendrerit.
          </p>
          <p>
            <a className="btn btn-secondary btn-sm float-end" href="/">
              Learn more <span className="fa fa-arrow-circle-right"></span>
            </a></p
        ></mat-card-content>
      </mat-card>

      ></mat-grid-tile
    >
    <mat-grid-tile
      rowspan="1"
      [colspan]="isMobile ? '1' : isTablet ? '3' : '6'"
    >
      <!-- <mat-list class="inline-list" role="list">
        <mat-list-item role="listitem">
          <a href="/" className="social-link" title="Twitter Profile">
            <mat-icon aria-hidden="false" aria-label="">twitter</mat-icon>
          </a>
        </mat-list-item>
        <mat-list-item role="listitem">
          <a href="/" className="social-link" title="Facebook Page">
            <mat-icon aria-hidden="false" aria-label="">facebook</mat-icon>
          </a>
        </mat-list-item>
        <mat-list-item role="listitem">
          <a href="/" className="social-link" title="LinkedIn Profile">
            <mat-icon aria-hidden="false" aria-label="">linkedIn</mat-icon>
          </a>
        </mat-list-item>
        <mat-list-item role="listitem">
          <a href="/" className="social-link" title="Google Profile">
<i class="fab fa-twitter"></i>
            <mat-icon aria-hidden="false" aria-label="">google</mat-icon>
          </a>
        </mat-list-item>
      </mat-list> -->
      <mat-toolbar layout="fill">
        <ng-container *ngIf="!isMobile">
          <span class="flex-spacer-half"></span>
        </ng-container>
        <!-- <span class="fill-space"></span> -->
        <a [href]="stackoverflowUrl" target="_blank">
          <img
            src="https://cdn4.iconfinder.com/data/icons/miu-hexagon-flat-social/60/stackoverflow-hexagon-social-media-32.png"
            alt=""
            matTooltip="StackOverflow"
            matTooltipPosition="above"
          />
        </a>
        <a [href]="twitterUrl" target="_blank">
          <img
            src="https://cdn4.iconfinder.com/data/icons/miu-hexagon-flat-social/60/twitter-hexagon-social-media-32.png"
            alt=""
            matTooltip="Twitter"
            matTooltipPosition="above"
          />
        </a>
        <a [href]="githubUrl" target="_blank">
          <img
            src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/github_six_color-32.png"
            alt=""
            matTooltip="Github"
            matTooltipPosition="above"
          />
        </a>
        <a [href]="facebookUrl" target="_blank">
          <img
            src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/Untitled-16-32.png"
            alt=""
            matTooltip="Facebook"
            matTooltipPosition="above"
          />
        </a>
        <a [href]="googleUrl" target="_blank">
          <img
            src="https://cdn4.iconfinder.com/data/icons/miu-hexagon-flat-social/60/google_plus-hexagon-social-media-32.png"
            alt=""
            matTooltip="Google+"
            matTooltipPosition="above"
          />
        </a>
        <a [href]="linkedinUrl" target="_blank">
          <img
            src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/Untitled-11-32.png"
            alt=""
            matTooltip="LinkedIn"
            matTooltipPosition="above"
          />
        </a>
        <span class="fill-space"></span>
      </mat-toolbar>
    </mat-grid-tile>
  </mat-grid-list>
</footer>
<footer>
  <mat-label> &copy; 2023 - Rumex Store Demo. See &nbsp;</mat-label>
  <a href="/">Privacy Policy</a>
</footer>

// rumexstore-react/src/Components/Footer.js
import React from 'react';
import { useSelector } from 'react-redux';
import { CategoryLinks } from './CategoryLinks';
import logo from '../assets/images/store-logo.png';

export const Footer = () => {
  const categories = [...useSelector((state) => state.products.categories)];
  if (categories && categories.length > 0) {
    if (
      !Boolean(
        categories.find(
          (x) => x.categoryName === 'All Departments' && x.id === -3,
        ),
      )
    ) {
      categories.push({
        categoryName: 'All Departments',
        id: -3,
        href: '/All Departments',
      });
    }
  }
  return (
    <footer role="contentinfo">
      <div className="container">
        <div className="row">
          <div className="col-md-4 col-lg-2">
            <h3>Categories</h3>
            <CategoryLinks
              // className="justify-content-start"
              categories={categories || []}
            />

            {/* <ul>
              <li>
                <a href="/">Shoes</a>
              </li>
              <li>
                <a href="/">Clothing</a>
              </li>
              <li>
                <a href="/">Accessories</a>
              </li>
              <li>
                <a href="/">Men</a>
              </li>
              <li>
                <a href="/">Women</a>
              </li>
              <li>
                <a href="/">Kids</a>
              </li>
              <li>
                <a href="/">Pets</a>
              </li>
            </ul> */}
          </div>
          <div className="col-md-4 col-lg-2">
            <h3>Styles</h3>
            <ul>
              <li>
                <a href="/">Athletic</a>
              </li>
              <li>
                <a href="/">Casual</a>
              </li>
              <li>
                <a href="/">Dress</a>
              </li>
              <li>
                <a href="/">Everyday</a>
              </li>
              <li>
                <a href="/">Other Days</a>
              </li>
              <li>
                <a href="/">Alternative</a>
              </li>
              <li>
                <a href="/">Otherwise</a>
              </li>
            </ul>
          </div>
          <div className="col-md-4 col-lg-2">
            <h3>Other</h3>
            <ul>
              <li>
                <a href="/">Link</a>
              </li>
              <li>
                <a href="/">Another link</a>
              </li>
              <li>
                <a href="/">Link again</a>
              </li>
              <li>
                <a href="/">Try this</a>
              </li>
              <li>
                <a href="/">Don't you dare</a>
              </li>
              <li>
                <a href="/">Oh go ahead</a>
              </li>
            </ul>
          </div>

          {/* <!-- Add the extra clearfix for only the required viewport --> */}
          {/* <div className="clearfix d-none d-md-block d-lg-none"></div> */}

          <div className="about col-xs-12 col-lg-6">
            <h3>About Us</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Suspendisse euismod congue bibendum. Aliquam erat volutpat.
              Phasellus eget justo lacus. Vivamus pharetra ullamcorper massa,
              nec ultricies metus gravida egestas. Duis congue viverra arcu, ac
              aliquet turpis rutrum a. Donec semper vestibulum dapibus. Integer
              et sollicitudin metus. Vivamus at nisi turpis. Phasellus vel
              tellus id felis cursus hendrerit.
            </p>
            <p>
              <a className="btn btn-secondary btn-sm float-end" href="/">
                Learn more <span className="fa fa-arrow-circle-right"></span>
              </a>
            </p>
          </div>
        </div>
        {/* <!-- /.row --> */}
      </div>
      {/* <!-- /.container --> */}

      <div className="container social-logo">
        <ul className="social">
          <li className="social-item">
            <a href="/" className="social-link" title="Twitter Profile">
              <i className="fa-brands fa-twitter"></i>
            </a>
          </li>
          <li className="social-item">
            <a href="/" className="social-link" title="Facebook Page">
              <i className="fa-brands fa-facebook"></i>
            </a>
          </li>
          <li className="social-item">
            <a href="/" className="social-link" title="LinkedIn Profile">
              <i className="fa-brands fa-linkedin"></i>
            </a>
          </li>
          <li className="social-item">
            <a href="/" className="social-link" title="Google Profile">
              <i className="fa-brands fa-google-plus"></i>
            </a>
          </li>
          <li className="social-item">
            <a href="/" className="social-link" title="GitHub Profile">
              <i className="fa-brands fa-github-alt"></i>
            </a>
          </li>
        </ul>

        <p>
          <a href="{{root}}index.html">
            <img src={logo} width="140" alt="Bootstrappin&#39;"></img>
          </a>
        </p>
      </div>
    </footer>
  );
};
